In [11]:
import numpy as np
import scipy.ndimage.filters as nd_filters


class OFilter:
    def __init__(self, order, mask_size, mode='symmetric'):
        self.order = order
        self.mask_size = mask_size
        self.mode = mode
        
    def local_filter(self, x):
        x.sort()
        return x[self.order]

    def ordfilt2(self, A):
        return nd_filters.generic_filter(A, self.local_filter, size=(self.mask_size, self.mask_size))

In [20]:
mpf_y = np.random.rand((3*4)).reshape(3,4)
mpf_y = np.array([
    [0.84530817, 0.79378528, 0.776688, 0.20166994],
     [0.12278887, 0.59674506, 0.83779851, 0.37469955],
     [0.98051769, 0.82292673, 0.40707693, 0.21811185],
     [0.98051769, 0.82292673, 0.40707693, 0.21811185]
])
NN_med=2
DD_med=2
Nr, Nc = mpf_y.shape
xp, yp = np.meshgrid(np.arange(Nc),np.arange(Nr))
F = OFilter(NN_med,DD_med,mode ='symmetric')
mpf_y = F.ordfilt2(mpf_y-yp) + yp
print(mpf_y)


[[0.84530817 0.84530817 0.79378528 0.776688  ]
 [1.84530817 1.79378528 1.776688   1.20166994]
 [1.12278887 1.12278887 1.59674506 1.37469955]
 [1.98051769 1.82292673 1.40707693 1.21811185]]


In [26]:
import cv2
cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(6,6))

array([[0, 0, 0, 1, 0, 0],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1]], dtype=uint8)

In [27]:
import matlab

ModuleNotFoundError: No module named 'matlab'